// react/sample-router-vite/src/Layout.jsx
import { Outlet, Link } from "react-router-dom";

const Layout = () => {
  const categories = [
    {
      name: "all",
      text: "전체보기",
    },
    {
      name: "business",
      text: "비즈니스",
    },
    {
      name: "entertainment",
      text: "엔터테인먼트",
    },
    {
      name: "health",
      text: "건강",
    },
    {
      name: "sport",
      text: "스포츠",
    },
    {
      name: "technology",
      text: "기술",
    },
  ];
  return (
    <>
      <header className="fixed top-0 left-0 right-0 bg-white shadow z-50">
        <div className="max-w-7xl mx-auto px-4 py-3 flex justify-between items-center">
          <h1 className="text-2xl font-bold text-gray-800">News Portal</h1>
          <nav className="space-x-4">
            {categories.map((category) => (
              <Link
                key={category}
                to={`/${category}`}
                className="text-gray-600 hover:text-blue-600 transition"
              >
                {category.text}
              </Link>
            ))}
          </nav>
        </div>
      </header>
      <main>
        <Outlet />
      </main>
      <footer className="fixed bottom-0 left-0 right-0 bg-gray-100 text-center py-3 text-sm text-gray-500 shadow-inner">
        © 2025 News Portal. All rights reserved.
      </footer>
    </>
  );
};

export default Layout;

// vue/vite-tailwind-app/src/Layout.vue
<template>
  <div class="min-h-screen flex flex-col">
    <!-- 헤더 -->
    <header
      class="bg-white shadow-md px-6 py-4 flex items-center justify-between"
    >
      <h1 class="text-xl font-bold text-gray-800">MyApp</h1>
      <nav class="flex items-center space-x-4">
        <RouterLink to="/userlist" class="text-gray-700 hover:text-blue-600">
          사용자 목록
        </RouterLink>
        <button
          @click="handleLogout"
          class="text-red-600 hover:text-red-700 font-medium"
        >
          로그아웃
        </button>
      </nav>
    </header>

    <!-- 메인 콘텐츠 -->
    <main class="flex-1 px-4 py-6 bg-gray-50">
      <router-view />
    </main>

    <!-- 푸터 -->
    <footer class="bg-gray-200 text-center py-4 text-sm text-gray-600">
      © 2025 MyApp. All rights reserved.
    </footer>
  </div>
</template>

<script setup>
import { useRouter } from "vue-router";

const router = useRouter();
const isLogin = localStorage.getItem("isLoggedIn");

if (isLogin != "true") router.push("/");

const handleLogout = () => {
  localStorage.removeItem("isLoggedIn");
  alert("로그아웃 되었습니다.");
  router.push("/login");
};
</script>
